### ISSUE TITLE
Installation on Windows with Anaconda

### ISSUE THREAD

**Issue by malj390** [shenlab-ucsf/SMART-Q#13]
Hello,

I'm having issues with MarkupSafe. Not sure if I could run this command properly as I'm using windows.
```
source .venv/bin/activate
pip install -e .
```
The command source doesn't exist in Powershell, so I just run activate (it went out of SMAR-Q env and I run the pip command. Everything seemed ok as the first line was calling SMAR-Q folder, but it stopped here.

```
Obtaining file:///C:/Users/User/SMART-Q                                                                               
Requirement already satisfied: alabaster==0.7.12 in c:\users\user\anaconda3\lib\site-packages (from starfish==0.0.31) (0.7.12)                                                                                                                Collecting apipkg==1.5                                                                                                    
Using cached apipkg-1.5-py2.py3-none-any.whl (4.9 kB) 
...
...
Collecting MarkupSafe==1.0
Using cached MarkupSafe-1.0.tar.gz (14 kB)
ERROR: Command errored out with exit status 1:
command: 'C:\Users\User\anaconda3\python.exe' -c 'import sys, setuptools, tokenize; 
sys.argv[0] = '"'"'C:\\Users\\User\\AppData\\Local\\Temp\\pip-install-ioqc9hap\\markupsafe_604fb5be103643dcb447ea37d4e4d416\\setup.py'"'"';
 __file__='"'"'C:\\Users\\User\\AppData\\Local\\Temp\\pip-install-ioqc9hap\\markupsafe_604fb5be103643dcb447ea37d4e4d416\\setup.py'"'"';
 f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();
 exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\User\AppData\Local\Temp\pip-pip-egg-info-rk5n6lnc'                                                                                                                     cwd: C:\Users\User\AppData\Local\Temp\pip-install-ioqc9hap\markupsafe_604fb5be103643dcb447ea37d4e4d416\          Complete output (5 lines):                                                                                              Traceback (most recent call last):                                                                                        File "<string>", line 1, in <module>                                                                                    File "C:\Users\User\AppData\Local\Temp\pip-install-ioqc9hap\markupsafe_604fb5be103643dcb447ea37d4e4d416\setup.py", line 6, in <module>                                                                                                          from setuptools import setup, Extension, Feature                                                                    ImportError: cannot import name 'Feature' from 'setuptools' (C:\Users\User\anaconda3\lib\site-packages\setuptools\__init__.py)                                                                                                                ----------------------------------------                                                                            WARNING: Discarding https://files.pythonhosted.org/packages/4d/de/32d741db316d8fdb7680822dd37001ef7a448255de9699ab4bfcbdf4172b/MarkupSafe-1.0.tar.gz#sha256=a6be69091dac236ea9c6bc7d012beab42010fa914c459791d627dad4910eb665 (from https://pypi.org/simple/markupsafe/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.ERROR: Could not find a version that satisfies the requirement MarkupSafe==1.0 (from starfish)
ERROR: No matching distribution found for MarkupSafe==1.0
```

Thank you! And congratulations for this work

**Comment by sethb3744** [comment]
Hi! Thank you for bringing this up. I searched and found this issue is likely related to some error within MarkupSafe based on [this issue submitted to MarkupSafe](https://github.com/pallets/markupsafe/issues/57) resolved in a later version. I updated the version requirements from MarkupSafe==1.0 to MarkupSafe==1.1.1 in requirements.txt. Try one more time and let me know if it works now.

**Comment by malj390** [comment]
To resume, for windows users, this is the command.
```
cd SMART-Q
python -m venv .venv
activate
pip install -e .
```
I still get an error of partial uninstallation though. Not sure if that will affect to the normal functioning.
```
Attempting uninstall: ipython                                                                                             
Found existing installation: ipython 7.22.0                                                                             
Uninstalling ipython-7.22.0:                                                                                              
Successfully uninstalled ipython-7.22.0                                                                             
Attempting uninstall: entrypoints                                                                                         
Found existing installation: entrypoints 0.3                                                                        
ERROR: Cannot uninstall 'entrypoints'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.
```
